server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tanya-marfel/yoke-service-config
          repos:
            yoke-notify:
              uri: https://github.com/tanya-marfel/yoke-notify-config
            yoke-event:
              uri: https://github.com/tanya-marfel/yoke-event-config
            yoke-attender:
              uri: https://github.com/tanya-marfel/yoke-attender-config